<?php

/**
 * @file
 * Importing menus, form and theme process functions.
 */

//require_once __DIR__ . '/includes/menus.inc';

function cpc_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  //var_dump($suggestions);
}

 /**
 * Implements hook_theme().
 */
/*function cpc_theme($existing, $type, $theme, $path) {
  return [
    'government_banner' => [
      'path' => $path . '/templates/uswds',
      'variables' => [
        'image_base' => [],
      ],
    ],
  ];
}*/
