<?php

/**
 * @file
 * Contains the drought_maps.module file.
 */


/**
 * Implements hook_leaflet_map_info().
 */
function drought_maps_leaflet_map_info() {

  $default_settings = [
    'attributionControl' => TRUE,
    'closePopupOnClick'  => TRUE,
    'doubleClickZoom'    => TRUE,
    'dragging'           => TRUE,
    'fadeAnimation'      => TRUE,
    'layerControl'       => FALSE,
    'maxZoom'            => 18,
    'minZoom'            => 0,
    'scrollWheelZoom'    => TRUE,
    'touchZoom'          => TRUE,
    'trackResize'        => TRUE,
    // Don't specify zoom, if you want to use Auto-box.
    // 'zoom'            =>  2,
    'zoomAnimation'      => TRUE,
    'zoomControl'        => TRUE,
  ];

  return [
    'Esri Dark Gray' =>
      [
        'label' => 'Esri Dark Gray',
        'description' => t('Esri dark gray basemap'),
        'settings' => $default_settings,
        'layers' => [
          'base' => [
            'urlTemplate' => '//{s}.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}.png',
            'options' => [
              'attribution' => 'Esri, HERE, Garmin, &copy; OpenStreetMap contributors, and the GIS User Community',
            ],
          ],
          'labels' => [
            'urlTemplate' => '//{s}.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Reference/MapServer/tile/{z}/{y}/{x}.png',
            'layer_type' => 'overlay',
            'options' => [
              'pane' => 'tilePane',
              'attribution' => '',
            ],
          ],
        ],
      ],
    'Esri Light Gray' =>
      [
        'label' => 'Esri Light Gray',
        'description' => t('Esri light gray basemap'),
        'settings' => $default_settings,
        'layers' => [
          'base' => [
            'urlTemplate' => '//{s}.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}.png',
            'options' => [
              'attribution' => 'Esri, HERE, Garmin, &copy; OpenStreetMap contributors, and the GIS User Community',
            ],
          ],
          'labels' => [
            'urlTemplate' => '//{s}.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer/tile/{z}/{y}/{x}.png',
            'layer_type' => 'overlay',
            'options' => [
              'pane' => 'tilePane',
              'attribution' => '',
            ],
          ],
        ],
      ],
  ];

}

/**
 * Implements hook_leaflet_views_feature_group_alter().
 */
function drought_maps_leaflet_views_feature_group_alter(array &$group, MarkerDefault $stylePlugin) {
  //ksm();
}
