<?php

/**
 * @file
 * Contains the drought_maps.module file.
 */


/**
 * Implements hook_leaflet_map_info().
 */
 
// Placeholder for now
 function drought_maps_leaflet_map_info() {
   return array(
     'Custom Maps' => array(
       'label' => 'Custom Map',
       'description' => t('Custom Map from Module'),
       'settings' => array(
         'dragging' => TRUE,
         'touchZoom' => TRUE,
         'scrollWheelZoom' => TRUE,
         'doubleClickZoom' => TRUE,
         'zoomControl' => TRUE,
         'attributionControl' => TRUE,
         'trackResize' => TRUE,
         'fadeAnimation' => TRUE,
         'zoomAnimation' => TRUE,
         'closePopupOnClick' => TRUE,
         'layerControl' => TRUE,
       ),

// Placeholder for now
     'layers' => array(
         'Open Street Map' => array(
           'urlTemplate' => 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
           'options' => array(
             'attribution' => '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
           ),
         ),
         'Open Topo Map' => array(
           'urlTemplate' => 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
           'options' => array(
             'attribution' => '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
           ),
         ),
         'Hillshade' => array(
           'urlTemplate' => 'https://maps.heigit.org/openmapsurfer/tiles/asterh/webmercator/{z}/{x}/{y}.png',
           'layer_type' => 'overlay', //this gives you the ability to overlay transparent maps
           'options' => array(
             'attribution' => 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> | Map data  <a href="https://lpdaac.usgs.gov/products/aster_policies">ASTER GDEM</a>, <a href="http://srtm.csi.cgiar.org/">SRTM</a>',
           ),
         ),
       ),
     ),
   );
 }
